//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Implemetr
    {
        public Implemetr()
        {
            this.request = new HashSet<request>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<request> request { get; set; }
    }
}
