//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int Id { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> idStatus { get; set; }
        public Nullable<System.DateTime> DateRequest { get; set; }
        public string Discription { get; set; }
        public Nullable<int> idType { get; set; }
        public string Oborud { get; set; }
        public string Comment { get; set; }
        public Nullable<int> idImplementer { get; set; }
    
        public virtual client client { get; set; }
        public virtual Implemetr Implemetr { get; set; }
        public virtual status status { get; set; }
        public virtual Type Type { get; set; }
    }
}
