//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.Implemetr = new HashSet<Implemetr>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<int> idRole { get; set; }
    
        public virtual ICollection<Implemetr> Implemetr { get; set; }
        public virtual role role { get; set; }
    }
}
